apiVersion: apps/v1
kind: Deployment
metadata:
  name: klinik
  namespace: klinik
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: klinik
  template:
    metadata:
      labels:
        app: klinik
    spec:
      containers:
      - name: klinik
        image: riqimaruq/belajariac:$BUILD_NUMBER
      automountServiceAccountToken: false
        resources:
        limits:
          memory: 100Mi
        ports:
        - name: web
          containerPort: 80
