apiVersion: apps/v1
kind: Deployment
metadata:
  name: akulaku
  namespace: aplikasi
spec:
  replicas: 1  # Sesuaikan jumlah replika sesuai kebutuhan
  selector:
    matchLabels:
      app: akulaku
  template:
    metadata:
      labels:
        app: akulaku
    spec:
      containers:
      - name: akulaku
        image: riqimaruq/akulaku:latest
        ports:
        - containerPort: 80  # Sesuaikan port jika berbeda
        resources:
          requests:
            memory: "10Mi"
            cpu: "250m"
          limits:
            memory: "100Mi"
            cpu: "500m"
