apiVersion: v1
kind: Service
metadata:
  name: klinik
  namespace: klinik
  labels:
    app: klinik
spec:
  type: LoadBalancer
  ports:
  - name:  http
    port:  80
    targetPort: 80
    protocol: TCP
  selector:
    app: klinik
